"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import { card } from "@/data/card";
import { qrMatrix } from "@/lib/qr";
import { downloadVCard } from "@/lib/vcard";
import { whatsappHref, whatsappOpeners } from "@/lib/site";
import { Mark } from "./Logo";
import { Arrow, WhatsAppGlyph } from "./Button";
import { playLock } from "@/lib/audio";

/**
 * THE CARD
 * ----------------------------------------------------------------------------
 * A contact card that behaves like an object rather than a page.
 *
 * It tilts. On a laptop it follows the pointer; on a phone it follows the
 * actual device, read from the accelerometer, so turning the handset turns the
 * card and moves the specular highlight across its face. That is the whole
 * trick: a business card is a physical thing, and this one has a surface that
 * catches the light.
 *
 * The QR code beside it is not an image and was not generated by a service. It
 * is computed in this browser, in this frame, by the encoder in lib/qr.ts —
 * Reed–Solomon and all — and drawn to a canvas module by module on a diagonal
 * wave. The mark is punched through the middle of it, which the code survives
 * because it is encoded at the highest error-correction level.
 *
 * Everything reduces properly: no pointer, no gyroscope, or reduced-motion
 * requested, and the card simply sits still and reads perfectly.
 */

const BONE = "#e8e7e1";

export function ContactCard() {
  const surfaceRef = useRef<HTMLDivElement>(null);
  const glowRef = useRef<HTMLDivElement>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [needsTiltPermission, setNeedsTiltPermission] = useState(false);
  const [tiltOn, setTiltOn] = useState(false);
  const [copied, setCopied] = useState(false);
  const [shareable, setShareable] = useState(false);
  const [portraitOk, setPortraitOk] = useState(true);

  const matrix = useMemo(() => qrMatrix(card.cardUrl, "H"), []);

  /* ------------------------------------------------------------------ tilt */

  useEffect(() => {
    const surface = surfaceRef.current;
    const glow = glowRef.current;
    if (!surface || !glow) return;

    const reduced = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    if (reduced) return;

    // Target and current are kept apart so the card eases rather than snaps.
    let targetX = 0;
    let targetY = 0;
    let x = 0;
    let y = 0;
    let frame = 0;
    let running = true;

    const loop = () => {
      if (!running) return;
      frame = window.requestAnimationFrame(loop);
      x += (targetX - x) * 0.08;
      y += (targetY - y) * 0.08;
      surface.style.transform = `rotateX(${(-y * 9).toFixed(3)}deg) rotateY(${(x * 11).toFixed(3)}deg)`;
      // The highlight travels the opposite way, the way a real one would.
      glow.style.transform = `translate3d(${(-x * 34).toFixed(2)}%, ${(-y * 26).toFixed(2)}%, 0)`;
      glow.style.opacity = String(0.30 + Math.min(Math.hypot(x, y), 1) * 0.35);
    };
    frame = window.requestAnimationFrame(loop);

    const onPointer = (event: PointerEvent) => {
      const rect = surface.getBoundingClientRect();
      targetX = (event.clientX - (rect.left + rect.width / 2)) / (rect.width / 2);
      targetY = (event.clientY - (rect.top + rect.height / 2)) / (rect.height / 2);
      targetX = Math.max(-1.4, Math.min(1.4, targetX));
      targetY = Math.max(-1.4, Math.min(1.4, targetY));
    };
    const onLeave = () => {
      targetX = 0;
      targetY = 0;
    };

    const onOrientation = (event: DeviceOrientationEvent) => {
      // gamma is the left-to-right tilt, beta the front-to-back one. Both are
      // clamped hard: a card you have to hold level to read is a bad card.
      const gamma = event.gamma ?? 0;
      const beta = event.beta ?? 45;
      targetX = Math.max(-1, Math.min(1, gamma / 30));
      targetY = Math.max(-1, Math.min(1, (beta - 45) / 35));
    };

    window.addEventListener("pointermove", onPointer, { passive: true });
    window.addEventListener("pointerleave", onLeave, { passive: true });

    const DOE = window.DeviceOrientationEvent as
      | (typeof DeviceOrientationEvent & { requestPermission?: () => Promise<string> })
      | undefined;

    if (DOE && typeof DOE.requestPermission === "function") {
      // iOS: the reader has to ask for it, from a gesture.
      setNeedsTiltPermission(true);
      (window as unknown as { __coreholdTilt?: () => void }).__coreholdTilt =
        () => {
          DOE.requestPermission?.()
            .then((state) => {
              if (state === "granted") {
                window.addEventListener("deviceorientation", onOrientation);
                setTiltOn(true);
                setNeedsTiltPermission(false);
              }
            })
            .catch(() => setNeedsTiltPermission(false));
        };
    } else if (DOE) {
      window.addEventListener("deviceorientation", onOrientation);
    }

    return () => {
      running = false;
      window.cancelAnimationFrame(frame);
      window.removeEventListener("pointermove", onPointer);
      window.removeEventListener("pointerleave", onLeave);
      window.removeEventListener("deviceorientation", onOrientation);
    };
  }, []);

  const askForTilt = useCallback(() => {
    (window as unknown as { __coreholdTilt?: () => void }).__coreholdTilt?.();
  }, []);

  /* -------------------------------------------------------------------- qr */

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    const size = matrix.length;
    const reduced = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    const KNOCKOUT = 9; // modules removed from the centre for the mark

    const half = KNOCKOUT / 2;
    const centre = size / 2;
    const isKnockedOut = (r: number, c: number) =>
      r + 1 > centre - half &&
      r < centre + half &&
      c + 1 > centre - half &&
      c < centre + half;

    let frame = 0;
    let start = 0;
    let running = true;

    const resize = () => {
      const dpr = Math.min(window.devicePixelRatio || 1, 3);
      const css = canvas.clientWidth;
      canvas.width = Math.round(css * dpr);
      canvas.height = Math.round(css * dpr);
    };

    const draw = (time: number) => {
      if (!running) return;
      if (!start) start = time;
      const t = (time - start) / 1000;

      const px = canvas.width;
      const unit = px / size;
      ctx.clearRect(0, 0, px, px);

      for (let r = 0; r < size; r += 1) {
        for (let c = 0; c < size; c += 1) {
          if (!matrix[r][c] || isKnockedOut(r, c)) continue;

          // The wave runs on the diagonal, so the code assembles from the
          // top-left finder outward rather than appearing all at once.
          const delay = ((r + c) / (size * 2)) * 0.85;
          const local = reduced ? 1 : Math.max(0, Math.min(1, (t - delay) / 0.32));
          if (local <= 0) continue;
          const eased = 1 - Math.pow(1 - local, 3);

          const inset = (1 - eased) * unit * 0.5;
          ctx.fillStyle = BONE;
          ctx.globalAlpha = 0.55 + eased * 0.45;
          ctx.fillRect(
            c * unit + inset,
            r * unit + inset,
            unit - inset * 2,
            unit - inset * 2,
          );
        }
      }
      ctx.globalAlpha = 1;

      // The highlight is a separate pass, screened over the finished code
      // rather than recolouring modules. A scanner thresholds light against
      // dark, and a band that turned light modules mid-orange would be a nice
      // effect that occasionally cost somebody a scan.
      if (!reduced) {
        const phase = ((t * 0.34) % 3.4) / 3.4;
        const travel = phase * (px * 2.2) - px * 0.6;
        const band = ctx.createLinearGradient(
          travel - px * 0.28,
          travel - px * 0.28,
          travel + px * 0.28,
          travel + px * 0.28,
        );
        band.addColorStop(0, "rgba(217,98,43,0)");
        band.addColorStop(0.5, "rgba(217,98,43,0.20)");
        band.addColorStop(1, "rgba(217,98,43,0)");
        ctx.globalCompositeOperation = "screen";
        ctx.fillStyle = band;
        ctx.fillRect(0, 0, px, px);
        ctx.globalCompositeOperation = "source-over";
      }

      if (reduced) return; // one frame is enough
      frame = window.requestAnimationFrame(draw);
    };

    resize();
    frame = window.requestAnimationFrame(draw);
    const onResize = () => {
      resize();
      start = 0;
    };
    window.addEventListener("resize", onResize, { passive: true });

    return () => {
      running = false;
      window.cancelAnimationFrame(frame);
      window.removeEventListener("resize", onResize);
    };
  }, [matrix]);

  /* --------------------------------------------------------------- actions */

  useEffect(() => {
    setShareable(typeof navigator !== "undefined" && "share" in navigator);
  }, []);

  const copyNumber = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(card.phoneDisplay);
      setCopied(true);
      playLock();
      window.setTimeout(() => setCopied(false), 2200);
    } catch {
      /* clipboard blocked — the number is on screen anyway */
    }
  }, []);

  const share = useCallback(async () => {
    try {
      await navigator.share({
        title: `${card.name} — ${card.org}`,
        text: card.claim,
        url: card.cardUrl,
      });
    } catch {
      /* dismissed */
    }
  }, []);

  /* ----------------------------------------------------------------- render */

  return (
    <div className="grid gap-12 lg:grid-cols-12 lg:gap-16">
      {/* ------------------------------------------------------- the object */}
      <div className="lg:col-span-7">
        <div className="card-perspective">
          <div ref={surfaceRef} className="card-surface">
            <div className="card-face">
              <div ref={glowRef} className="card-glow" aria-hidden="true" />

              <div className="relative flex flex-col gap-8 p-7 sm:flex-row sm:items-start sm:gap-9 sm:p-9">
                <div className="card-portrait shrink-0">
                  {portraitOk ? (
                    // eslint-disable-next-line @next/next/no-img-element
                    <img
                      src={card.portrait}
                      alt={`${card.name}, ${card.title} of ${card.org}`}
                      width={520}
                      height={640}
                      onError={() => setPortraitOk(false)}
                      className="h-full w-full object-cover object-top"
                    />
                  ) : (
                    <div className="flex h-full w-full items-center justify-center bg-quarry-900">
                      <Mark className="h-10 w-10 text-oxide" title={card.org} />
                    </div>
                  )}
                  <span className="card-portrait-tint" aria-hidden="true" />
                  <span className="card-scan" aria-hidden="true" />
                </div>

                <div className="min-w-0 flex-1">
                  <p className="tag card-in text-quarry-400">{card.line}</p>

                  <h1 className="card-in mt-4 text-[clamp(1.9rem,6vw,2.6rem)] leading-[1.02] tracking-[-0.035em] text-bone" style={{ animationDelay: "80ms" }}>
                    {card.name}
                  </h1>

                  <p className="card-in mt-2.5 text-lg tracking-[-0.02em] text-oxide" style={{ animationDelay: "140ms" }}>
                    {card.title}
                    <span className="text-quarry-500"> · </span>
                    <span className="text-quarry-300">{card.org}</span>
                  </p>

                  <p className="card-in mt-6 max-w-[34ch] text-[0.9375rem] leading-relaxed text-quarry-300" style={{ animationDelay: "200ms" }}>
                    {card.claim} We build the core your company operates on, then
                    hand you the deed to it.
                  </p>

                  <dl className="card-in mt-7 grid gap-x-8 gap-y-3 border-t border-quarry-800 pt-6 font-mono text-xs sm:grid-cols-2" style={{ animationDelay: "260ms" }}>
                    <div>
                      <dt className="text-quarry-500">Mobile</dt>
                      <dd className="mt-1 text-bone">{card.phoneDisplay}</dd>
                    </div>
                    <div>
                      <dt className="text-quarry-500">Email</dt>
                      <dd className="mt-1 break-all text-bone">{card.email}</dd>
                    </div>
                    <div>
                      <dt className="text-quarry-500">Studio</dt>
                      <dd className="mt-1 text-bone">
                        {card.city}, {card.country}
                      </dd>
                    </div>
                    <div>
                      <dt className="text-quarry-500">Web</dt>
                      <dd className="mt-1 text-bone">{card.websiteDisplay}</dd>
                    </div>
                  </dl>
                </div>
              </div>

              <div className="card-rule" aria-hidden="true" />

              <div className="flex items-center justify-between gap-4 px-7 py-5 sm:px-9">
                <Mark className="h-5 w-5 text-oxide" aria-hidden="true" />
                <p className="font-mono text-[0.6875rem] tracking-[0.12em] text-quarry-500 uppercase">
                  No licences. No lock-in. No landlord.
                </p>
              </div>
            </div>
          </div>
        </div>

        {needsTiltPermission && (
          <button
            type="button"
            onClick={askForTilt}
            className="mt-5 inline-flex items-center gap-2.5 font-mono text-xs text-quarry-400 underline underline-offset-4 transition-colors hover:text-oxide"
          >
            Let the card follow your phone
          </button>
        )}
        {tiltOn && (
          <p className="mt-5 font-mono text-xs text-quarry-500">
            Tilt your phone — the card is holding the light.
          </p>
        )}
      </div>

      {/* ---------------------------------------------------------- actions */}
      <div className="lg:col-span-5">
        <div className="flex flex-col gap-3">
          <a
            href={whatsappHref(whatsappOpeners.general)}
            target="_blank"
            rel="noopener noreferrer"
            className="card-action card-action-primary card-in"
          >
            <WhatsAppGlyph className="h-5 w-5" />
            <span className="flex-1">WhatsApp</span>
            <span className="latin font-mono text-xs">
              {card.phoneDisplay}
            </span>
          </a>

          <a href={`tel:${card.phone}`} className="card-action card-in" style={{ animationDelay: "60ms" }}>
            <PhoneGlyph />
            <span className="flex-1">Call</span>
            <span className="latin font-mono text-xs text-quarry-500">
              {card.phoneDisplay}
            </span>
          </a>

          <a href={`mailto:${card.email}`} className="card-action card-in" style={{ animationDelay: "100ms" }}>
            <MailGlyph />
            <span className="flex-1">Email</span>
            <span className="font-mono text-xs text-quarry-500">
              {card.email}
            </span>
          </a>

          <button
            type="button"
            onClick={() => {
              downloadVCard();
              playLock();
            }}
            className="card-action card-in text-left"
            style={{ animationDelay: "140ms" }}
          >
            <CardGlyph />
            <span className="flex-1">Save to contacts</span>
            <span className="font-mono text-xs text-quarry-500">.vcf</span>
          </button>

          <div className="mt-2 grid grid-cols-2 gap-3">
            <a
              href={card.linkedin}
              target="_blank"
              rel="noopener noreferrer"
              className="card-action card-in justify-center"
              style={{ animationDelay: "180ms" }}
            >
              <LinkedInGlyph />
              <span>LinkedIn</span>
            </a>
            <a
              href={card.x}
              target="_blank"
              rel="noopener noreferrer"
              className="card-action card-in justify-center"
              style={{ animationDelay: "210ms" }}
            >
              <XGlyph />
              <span className="truncate">coreholdsystems</span>
            </a>
          </div>

          <div className="mt-2 grid grid-cols-2 gap-3">
            <button
              type="button"
              onClick={copyNumber}
              className="card-action card-in justify-center"
              style={{ animationDelay: "240ms" }}
            >
              <span>{copied ? "Copied" : "Copy number"}</span>
            </button>
            {shareable ? (
              <button
                type="button"
                onClick={share}
                className="card-action card-in justify-center"
                style={{ animationDelay: "270ms" }}
              >
                <span>Share card</span>
              </button>
            ) : (
              <Link
                href="/"
                className="card-action card-in justify-center"
                style={{ animationDelay: "270ms" }}
              >
                <span>The studio</span>
                <Arrow />
              </Link>
            )}
          </div>
        </div>

        {/* ------------------------------------------------------------- qr */}
        <div className="card-in mt-10 border border-quarry-800 bg-quarry-900 p-6" style={{ animationDelay: "320ms" }}>
          <div className="flex items-start gap-6">
            <div className="relative h-[132px] w-[132px] shrink-0 sm:h-[148px] sm:w-[148px]">
              <canvas
                ref={canvasRef}
                aria-hidden="true"
                className="h-full w-full"
              />
              <span className="pointer-events-none absolute inset-0 flex items-center justify-center">
                <Mark className="h-7 w-7 text-oxide sm:h-8 sm:w-8" aria-hidden="true" />
              </span>
            </div>
            <div className="min-w-0">
              <p className="tag text-quarry-500">Scan or pass it on</p>
              <p className="mt-3 text-[0.9375rem] leading-relaxed text-quarry-300">
                Points at this card. Hold it up and someone else can take it
                from your screen.
              </p>
              <p className="mt-3 font-mono text-xs break-all text-quarry-500">
                {card.cardUrl.replace("https://", "")}
              </p>
            </div>
          </div>
          <p className="mt-6 border-t border-quarry-800 pt-4 font-mono text-[0.6875rem] leading-relaxed text-quarry-500">
            This code was generated in your browser by {matrix.length}×
            {matrix.length} of our own arithmetic — Reed–Solomon over GF(256), no
            library, no service. The mark is punched through the middle and it
            still scans, because it is encoded at the highest correction level.
          </p>
        </div>
      </div>
    </div>
  );
}

/* ------------------------------------------------------------------ glyphs */

function PhoneGlyph() {
  return (
    <svg viewBox="0 0 16 16" fill="none" aria-hidden="true" className="h-4 w-4 shrink-0">
      <path
        d="M5.2 2.5 6.6 5.4 5.1 6.9a8.4 8.4 0 0 0 4 4l1.5-1.5 2.9 1.4v2.4c-6 0-10.9-4.9-10.9-10.9h2.6Z"
        stroke="currentColor"
        strokeWidth="1.3"
        strokeLinejoin="round"
      />
    </svg>
  );
}

function MailGlyph() {
  return (
    <svg viewBox="0 0 16 16" fill="none" aria-hidden="true" className="h-4 w-4 shrink-0">
      <rect x="1.6" y="3.4" width="12.8" height="9.2" stroke="currentColor" strokeWidth="1.3" />
      <path d="m1.9 4 6.1 4.4L14.1 4" stroke="currentColor" strokeWidth="1.3" />
    </svg>
  );
}

function CardGlyph() {
  return (
    <svg viewBox="0 0 16 16" fill="none" aria-hidden="true" className="h-4 w-4 shrink-0">
      <rect x="1.6" y="3.4" width="12.8" height="9.2" stroke="currentColor" strokeWidth="1.3" />
      <circle cx="5.6" cy="7.2" r="1.5" stroke="currentColor" strokeWidth="1.2" />
      <path d="M3.2 11c.5-1.3 1.4-1.9 2.4-1.9s1.9.6 2.4 1.9M9.6 6.6h3.2M9.6 9h3.2" stroke="currentColor" strokeWidth="1.2" />
    </svg>
  );
}

function LinkedInGlyph() {
  return (
    <svg viewBox="0 0 16 16" fill="currentColor" aria-hidden="true" className="h-4 w-4 shrink-0">
      <path d="M3.6 5.4H1.4V14h2.2V5.4ZM2.5 1.9a1.3 1.3 0 1 0 0 2.6 1.3 1.3 0 0 0 0-2.6ZM14.6 9.1c0-2.3-1.2-3.9-3.2-3.9-1.1 0-1.8.6-2.1 1.2V5.4H7.1c0 .6 0 8.6 0 8.6h2.2V9.3c0-.2 0-.4.1-.6.2-.5.6-1 1.3-1 .9 0 1.4.7 1.4 1.8V14h2.2V9.1Z" />
    </svg>
  );
}

function XGlyph() {
  return (
    <svg viewBox="0 0 16 16" fill="currentColor" aria-hidden="true" className="h-4 w-4 shrink-0">
      <path d="M11.9 1.7h2.2L9.3 7.2l5.7 7.1h-4.5L7 9.9l-4 4.4H.8l5.2-5.8L.5 1.7H5l3.1 4.1 3.8-4.1Zm-.8 11.3h1.2L4.9 2.9H3.6l7.5 10.1Z" />
    </svg>
  );
}
