import Link from "next/link";
import { Reveal } from "./Reveal";
import { Arrow } from "./Button";

/**
 * What a studio publishes is a truer signal than what it claims. This is the
 * index of everything Corehold has put in the open — the worked audit, the
 * verdicts, the commitments, the argument, the identity and the site's own
 * specification.
 */
const PUBLISHED: [string, string, string, string][] = [
  [
    "01",
    "A specimen audit",
    "/specimen",
    "The deliverable, published in full. Eight pages, downloadable, composite scenario — because we will not invent a client.",
  ],
  [
    "02",
    "The Register",
    "/register",
    "Build it or rent it, across forty-three categories of business software — with the lock-in risk and the point at which each verdict flips.",
  ],
  [
    "03",
    "The Corehold Standard",
    "/standard",
    "Six commitments, how to verify each one, and the engagement terms in plain English. Versioned, dated, and open to being held against us.",
  ],
  [
    "04",
    "The manifesto",
    "/manifesto",
    "The argument in eight chapters, for the version of this conversation that happens without us in the room.",
  ],
  [
    "05",
    "The brand standard",
    "/brand",
    "The identity in the open: mark, colour, type, motion and voice — with the business documents generated by the site itself.",
  ],
  [
    "06",
    "This site's specification",
    "/system",
    "Measured budgets, the reasoning behind every engineering decision, the full token table, and the commands to check all of it.",
  ],
];

export function PublishedIndex() {
  return (
    <div className="mt-14 grid gap-px border border-quarry-800 bg-quarry-800 lg:mt-16 md:grid-cols-2 lg:grid-cols-3">
      {PUBLISHED.map(([index, title, href, body], i) => (
        <Reveal key={href} delay={i * 40}>
          <Link
            href={href}
            className="group flex h-full flex-col bg-quarry-950 p-7 transition-colors duration-300 hover:bg-quarry-900 lg:p-8"
          >
            <span className="tag text-oxide">{index}</span>
            <span className="mt-5 flex items-baseline gap-3 text-lg tracking-[-0.02em] text-bone">
              {title}
              <Arrow className="text-quarry-500 transition-colors group-hover:text-oxide" />
            </span>
            <span className="mt-3 flex-1 text-[0.9375rem] leading-relaxed text-quarry-400">
              {body}
            </span>
          </Link>
        </Reveal>
      ))}
    </div>
  );
}
