/**
 * The site's own specification.
 *
 * Every number in here is measured from the production build in this
 * repository, not estimated. When the build changes, this file changes with
 * it — publishing a stale spec sheet would be worse than publishing none.
 */

export const measured = {
  buildDate: "2026-08-10",
  routes: 23,
  nextVersion: "15.5",
  reactVersion: "19.2",
  sharedJs: "103 kB",
  heaviestRoute: { path: "/", value: "125 kB" },
  lightestRoute: { path: "/ar", value: "107 kB" },
  runtimeDependencies: 3,
  totalDependencies: 3,
  fontFiles: 6,
  fontWeight: "198 kB across two scripts",
  thirdPartyRequests: 0,
  cookies: 0,
  trackers: 0,
  images: 1,
  audioFiles: 0,
  particles: 200_000,
  renderPasses: 6,
  prerenderedRoutes: 22,
  axeViolations: 0,
  axeRuleSets: ["wcag2a", "wcag2aa", "wcag21a", "wcag21aa", "best-practice"],
  axePages: 18,
  axeViewports: ["1440px", "390px"],
} as const;

export const budgets: [string, string, string][] = [
  [
    "Runtime dependencies",
    `${measured.runtimeDependencies}`,
    "next, react, react-dom. No UI kit, no animation library, no icon package, no charting library, no PDF library.",
  ],
  [
    "Shared first-load JavaScript",
    measured.sharedJs,
    "Framework and router. Everything this site adds on top of that — the graph, the switch, the palette, the model — is measured in single-digit kilobytes.",
  ],
  [
    "Third-party requests at runtime",
    `${measured.thirdPartyRequests}`,
    "No font CDN, no analytics, no tag manager, no embedded widgets. The page is served entirely from its own origin.",
  ],
  [
    "Cookies set",
    `${measured.cookies}`,
    "There is no consent banner on this site because there is nothing to consent to.",
  ],
  [
    "Raster images in the layout",
    `${measured.images}`,
    "One: the Open Graph card, which never loads in the page. Every mark, diagram and chart is vector or canvas.",
  ],
  [
    "The homepage, in full",
    "13.2 kB",
    "Including the renderer, the raymarched carve, a 200,000-particle GPU simulation, the six-pass film chain, the kill-switch demonstration and both counters. A single 3D library would be forty times that on its own, before any of this was written.",
  ],
  [
    "Audio files",
    "0",
    "Every sound on the site is synthesised in the browser from oscillators and generated noise. There is nothing to download and nothing to buffer.",
  ],
  [
    "Latin critical font weight",
    "64 kB",
    "Three files, self-hosted. The Arabic face loads only on the Arabic edition and never blocks a Latin page.",
  ],
  [
    "axe-core violations",
    `${measured.axeViolations}`,
    `Across ${measured.axePages} pages at ${measured.axeViewports.join(" and ")}, under ${measured.axeRuleSets.join(", ")}.`,
  ],
];

export const decisions: [string, string][] = [
  [
    "WebGL2 by hand, not a 3D library",
    "The homepage runs a real renderer: a rasterised pass writing colour and screen-space velocity into two attachments, a raymarched pass with no geometry at all, a GPU particle simulation, and a composite. There is an excellent library for all of this and the site does not use it, because importing six hundred kilobytes would make the dependency count on this page a lie. Matrices, framebuffers, shaders and meshes, written here.",
  ],
  [
    "The mark is carved, not modelled",
    "The object in the last beat is a signed distance field: a solid block of stone, the mark, and a cutting plane that sweeps down and decides which of the two each point in space belongs to. Soft shadows come from marching a second ray at the light; ambient occlusion from five samples along the normal. No vertices are involved in any of it — the entire image is one triangle and one function, and that function is published and editable on this page.",
  ],
  [
    "Two hundred thousand particles, one draw call",
    "The swarm is simulated with transform feedback, the WebGL2 feature that lets a vertex shader write its results back into a buffer instead of rasterising them. The simulation is therefore a draw call with the rasteriser switched off: no state textures, no readback, and no per-particle work on the CPU after the first frame.",
  ],
  [
    "A film pass, not a filter",
    "Motion blur is sampled along a real per-pixel velocity vector written by the geometry pass, not faked with a trailing ghost. Depth of field reads the same buffer's linear depth. Bloom and the out-of-focus field share one blurred copy of the frame rather than two, which is where most of the cost of a post chain usually goes.",
  ],
  [
    "Sound with no audio files",
    "The room tone is two detuned sine partials over integrated noise; the lock is a filtered burst with a pitched body; the kill switch is a sub-bass fall. All generated by the Web Audio API at runtime. It is silent until you ask for it, because audio that starts on its own is the fastest way to make an expensive thing feel cheap.",
  ],
  [
    "The homepage argues once, then stops",
    "An earlier version of this page carried every section the site has. It was complete and it was exhausting. The homepage now runs six beats — one idea each, one screen each — and every piece of depth lives on the page built for it. Nothing was deleted; it was moved somewhere a reader arrives on purpose.",
  ],
  [
    "Seeded randomness",
    "The 'mess' in the graph is generated from a fixed seed, so it is identical on every load, every device and every screenshot. A brand built on determinism should not shuffle itself per visitor.",
  ],
  [
    "Scroll read into refs, never state",
    "Scroll-driven pieces write transforms straight to the DOM from a single requestAnimationFrame loop that is gated by an IntersectionObserver. Scrolling this site does not re-render React, and nothing animates off-screen.",
  ],
  [
    "A hand-written PDF writer",
    "The rent exposure sheet is a real PDF, produced by about 120 lines in the browser using the base-14 fonts. Pulling in a 300 kB library to lay out one page of text and hairlines would have contradicted the argument on the rest of the site.",
  ],
  [
    "Native disclosure for the FAQ",
    "Details and summary elements, styled. Correct in every screen reader and every engine at zero JavaScript cost, which a bespoke accordion cannot claim.",
  ],
  [
    "No View Transitions API",
    "It is still unevenly implemented across engines. The route transition here is CSS, so Firefox, Safari, Chrome, Edge and Brave all get the same result rather than two of them getting a nicer one.",
  ],
  [
    "Fonts vendored into the repository",
    "Nothing is fetched from a font CDN at runtime. One less third party in the critical path, and one fewer contradiction for a studio that argues against renting your infrastructure.",
  ],
  [
    "Motion has an off switch that we honour",
    "prefers-reduced-motion is not a token gesture here: the dependency graph collapses to a single composed frame, the core sample renders complete, the boot sequence never plays, and every reveal resolves instantly.",
  ],
];

export const tokens: { group: string; rows: [string, string, string][] }[] = [
  {
    group: "Ground",
    rows: [
      ["quarry-950", "#0b0d0c", "Base ground. Mineral near-black, green-grey cast."],
      ["quarry-900", "#101312", "Raised ground for alternating sections."],
      ["quarry-800", "#191e1c", "Hairline rules and panel borders."],
      ["quarry-500", "#7a827d", "Technical labels. 4.9:1 on the base ground."],
      ["quarry-300", "#aeb4af", "Secondary prose. 9.1:1."],
      ["bone", "#e8e7e1", "Primary text on dark. 15.9:1."],
    ],
  },
  {
    group: "Paper",
    rows: [
      ["limestone", "#efede8", "Light ground. Used twice, both times for a document."],
      ["limestone-line", "#cbc6bc", "Hairlines on paper."],
      ["quarry-600", "#313835", "Labels on paper. 10.2:1."],
    ],
  },
  {
    group: "Signal",
    rows: [
      ["oxide", "#d9622b", "The only accent. Load-bearing elements only."],
      ["oxide-deep", "#a8461b", "The accent on paper, where the brighter one would fail contrast."],
      ["oxide-bright", "#ee7a41", "Hover state."],
    ],
  },
  {
    group: "Type & motion",
    rows: [
      ["--font-display", "Archivo", "Display, UI and body. One family, whole site."],
      ["--font-mono", "IBM Plex Mono", "Sheet numbers, labels, readouts, manifests."],
      ["--ease-structural", "cubic-bezier(.22,.68,.24,1)", "The single easing curve. Nothing bounces."],
    ],
  },
];
